// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HiddenloadingController from "./hiddenloading_controller"
application.register("hiddenloading", HiddenloadingController)

import ToggleElementController from "./toggle_element_controller"
application.register("toggle-element", ToggleElementController)
