// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckedIconController from "./checked_icon_controller"
application.register("checked-icon", CheckedIconController)

import CountermaxController from "./countermax_controller"
application.register("countermax", CountermaxController)

import DreamController from "./dream_controller"
application.register("dream", DreamController)

import DreamfeedController from "./dreamfeed_controller"
application.register("dreamfeed", DreamfeedController)

import GradientController from "./gradient_controller"
application.register("gradient", GradientController)

import HiddenloadingController from "./hiddenloading_controller"
application.register("hiddenloading", HiddenloadingController)

import HomepageController from "./homepage_controller"
application.register("homepage", HomepageController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ToggleElementController from "./toggle_element_controller"
application.register("toggle-element", ToggleElementController)
